[package]
name = "rust-part"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["full"]}
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
rustls-pemfile = "2.2.0"
rustls = "0.23.37"  #